"""create initial database schema

Revision ID: 1433acd25362
Revises: 
Create Date: 2026-08-09 15:41:46.121083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1433acd25362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lsa_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lsa_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lsa_profiles_is_active'), ['is_active'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_email'), ['email'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('lsa_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lsa_id'], ['lsa_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.create_index('ix_booking_lsa_time', ['lsa_id', 'start_time', 'end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_lsa_id'), ['lsa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_status'), ['status'], unique=False)

    op.create_table('lsa_skills',
    sa.Column('lsa_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lsa_id'], ['lsa_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lsa_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lsa_skills')
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_requests_status'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_parent_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_lsa_id'))
        batch_op.drop_index('ix_booking_lsa_time')

    op.drop_table('booking_requests')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_email'))

    op.drop_table('parents')
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_email'))

    op.drop_table('lsa_profiles')
    # ### end Alembic commands ###
